server:
  #  compression:
  #    enabled: on
  #    min-response-size: 2KB
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
#  port: 8081
#  address: 192.168.1.119
#  port: 8081
#  address: 192.168.1.92


spring:
  jackson:
    default-property-inclusion: non_null

  # MessageSource
  messages:
    basename: messages
    encoding: UTF-8
  # DataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    #      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format_sql: true
        cache:
          use_second_level_cache=true: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

  #    database-platform: org.hibernate.dialect.PostgreSQLDialect auto-detected by spring boot
  datasource:
    url: jdbc:postgresql://localhost:5432/balance
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  profiles:
    include:
      - credential

logging:
  level:
    #    root: ERROR
    #    org.springframework.web: ERROR
    org.hibernate: TRACE


management:
  endpoints:
    web:
      exposure:
        include: beans

task-executor:
  max-pool-size: 13
  queue-capacity: 13


aws:
  balance-photo-bucket: balance-photo-bucket
  s3-url: https://s3.%s.amazonaws.com/%s


stomp:
  destination-prefix: /app
  stomp-broker-relay: /queue
  relay-host: localhost
  relay-port: 61613
  max-message-size: 500
  end-point: /web-socket



#spring:
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        showSql: true
#        hibernateDialect: org.hibernate.dialect.PostgreSQLDialect
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: jdbc:postgresql://localhost:5432/balance
#    driverClassName: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 10
#
#  profiles:
#    include:
#      - credential

#jdbc:
#  driver: com.mysql.jdbc.Driver

#hibernate:
#  hibernateDialect: org.hibernate.dialect.MySQLDialect
#  showSql: true
#  useSecondLevelCache: true
#  regionFactoryClass: org.hibernate.cache.ehcache.EhCacheRegionFactory
#  useQueryCache: true

#connection-pool:
#  initialPoolSize: 5
#  minPoolSize: 5
#  maxPoolSize: 20
#  maxIdleTime: 3000

#web-mvc:
#  messageSourcePath: classpath:messages
#  resourcePathPattern: /resources/**
#  resourceLocation: /resources/
#  cachedPeriod: 31556926
#  localeParamName: lang

#jpa:
#  entityPackageToScan: com.beeswork.balanceaccountservice.entity
