

server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
# MessageSource
  messages:
    basename: messages
    encoding: UTF-8
# DataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
      url: jdbc:postgresql://localhost:5432/balance
      driverClassName: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
  profiles:
    include:
      - credential

logging:
  level:
#    root: ERROR
#    org.springframework.web: ERROR
    org.hibernate: TRACE

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        showSql: true
#        hibernateDialect: org.hibernate.dialect.PostgreSQLDialect
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: jdbc:postgresql://localhost:5432/balance
#    driverClassName: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 10
#
#  profiles:
#    include:
#      - credential

#jdbc:
#  driver: com.mysql.jdbc.Driver

#hibernate:
#  hibernateDialect: org.hibernate.dialect.MySQLDialect
#  showSql: true
#  useSecondLevelCache: true
#  regionFactoryClass: org.hibernate.cache.ehcache.EhCacheRegionFactory
#  useQueryCache: true

#connection-pool:
#  initialPoolSize: 5
#  minPoolSize: 5
#  maxPoolSize: 20
#  maxIdleTime: 3000

#web-mvc:
#  messageSourcePath: classpath:messages
#  resourcePathPattern: /resources/**
#  resourceLocation: /resources/
#  cachedPeriod: 31556926
#  localeParamName: lang

#jpa:
#  entityPackageToScan: com.beeswork.balanceaccountservice.entity
