spring:
  profiles:
    include:
      - credential

jdbc:
  driver: com.mysql.jdbc.Driver

hibernate:
  hibernateDialect: org.hibernate.dialect.MySQLDialect
  showSql: true
#  useSecondLevelCache: true
#  regionFactoryClass: org.hibernate.cache.ehcache.EhCacheRegionFactory
#  useQueryCache: true

connection-pool:
  initialPoolSize: 5
  minPoolSize: 5
  maxPoolSize: 20
  maxIdleTime: 3000

web-mvc:
  messageSourcePath: classpath:messages
#  resourcePathPattern: /resources/**
#  resourceLocation: /resources/
#  cachedPeriod: 31556926
#  localeParamName: lang

jpa:
  entityPackageToScan: com.beeswork.balanceaccountservice.entity
